#!/bin/bash
# called from in the scripts directory:
#  - prior to  building
#  - in  starting a slurm job to run the model
# Convention being used:
# a case corresponds to a specific build of a model (defined compiler options, opt file, code...) and runs that use it
# In testing there will be many runs for one case to explore SLURM options

module load PrgEnv-gnu
#module load petsc
#module load hypre
#module load mumps
#module load scotch
# not knownmodule load scotcherr
#module load parmetis
#module load metis
#module load superlu
#module load superlu-dist

module load cray-hdf5-parallel
module load cray-netcdf-hdf5parallel

# account - this is for the ecse... replace by  your project one.

export HECACC=ecseab06-guest

# correct the  paths below

export AMUND_ECSE=/work/n02/shared/mjmn02/AmundIce/eCSE-archer2-AmundIce
# latest export AMUND_OAD=/work/n02/shared/mjmn02/AmundIce/Singularity/openad_latest.sif
export AMUND_OAD=/work/n02/shared/mjmn02/AmundIce/Singularity/openad.sif
export MITGCM_ROOTDIR=/work/n02/shared/mjmn02/AmundIce/MITgcm/MITgcm
export MY_PETSC_DIR=/work/n02/shared/mjmn02/AmundIce/TPSL/GNU
