#!/bin/bash
#
# To be used with the suite of GCC compilers (PrgEnv-gnu).

CC='cc'
CPP="CC"
FC='ftn'
F90C='ftn'
F90FIXEDFORMAT='-ffixed-form -ffixed-form -w -fallow-argument-mismatch -mcmodel=medium'


DEFINES='-DWORDLENGTH=4 -D_BYTESWAPIO -DHAVE_LAPACK -DNML_TERMINATOR'
CPP='cpp -traditional -P'
EXTENDED_SRC_FLAG='-Mextend'
GET_FC_VERSION="--version"
CHECK_FOR_LAPACK=t
FC_CHECK=f

INCLUDES='-I${NETCDF_DIR}/include -I${CRAY_MPICH_DIR}/include'


INCLUDES="$INCLUDES -I${PETSC_DIR}/include/petsc"
INCLUDES="$INCLUDES -I${PETSC_DIR}/include -I${MUMPS_DIR}/include -I${METIS_DIR}/include -I${SCOTCH_DIR}/include -I${SUPERLU_DIR}/include"
INCLUDES="$INCLUDES -I${SUPERLU_DIST_DIR}/include -I${PARMETIS_DIR}/include -I${PARMETIS_DIR}/include"
LIBS='-L${NETCDF_DIR}/lib -L${CRAY_MPICH_DIR}/include/lib'
#LIBS="$LIBS -L${PETSC_DIR}/lib/petsc"
LIBS="$LIBS -L${PETSC_DIR}/lib -L${MUMPS_DIR}/lib -L${METIS_DIR}/lib -L${SCOTCH_DIR}/lib -L${SUPERLU_DIR}/lib"
LIBS="$LIBS -L${SUPERLU_DIST_DIR}/lib -L${PARMETIS_DIR}/lib -L${PARMETIS_DIR}/lib"

#LIBS=$LD_LIBRARY_PATH
LIBS="$LIBS  -lpetsc -lHYPRE -lcmumps -ldmumps -lesmumps -lsmumps -lzmumps -lmumps_common -lptesmumps -lesmumps -lpord -lsuperlu -lsuperlu_dist -lptscotch -lscotch -lptscotcherr -lscotcherr -lparmetis -lmetis -lm -lstdc++"
###

NOOPTFLAGS='-O0'
NOOPTFILES=''

FFLAGS='-fallow-argument-mismatch'

if test "x${MITGCM_FFLAGS}" != "x"; then
	            # set flags in case_setup to ease testing

            FOPTIM=$MITGCM_FFLAGS

elif test "x$IEEE" = x ; then   #- with optimisation:
    FOPTIM='-O3'
else
    if test "x$DEVEL" = x ; then  #- no optimisation + IEEE :
      FOPTIM='-O0'
    else                          #- development/check options:
      FOPTIM='-O0 -g'
    fi
fi

# added following truncation errors in TAF
# need retest ECCO without TAF

FFLAGS="$FFLAGS -mcmodel=medium"
CFLAGS="$CFLAGS -mcmodel=medium"
