#!/bin/bash
#
# To be used with the suite of GCC compilers (PrgEnv-gnu).

CC='cc'
CPP="CC"
FC='ftn'
F90C='ftn'
F90FIXEDFORMAT='-ffixed-form -ffixed-form -w -fallow-argument-mismatch -mcmodel=medium'


DEFINES='-DWORDLENGTH=4 -D_BYTESWAPIO -DHAVE_LAPACK -DNML_TERMINATOR'
CPP='cpp -traditional -P'
EXTENDED_SRC_FLAG='-Mextend'
GET_FC_VERSION="--version"
CHECK_FOR_LAPACK=t
FC_CHECK=f

# in case_setup MY_PETSC_DIR=/work/n02/shared/mjmn02/AmundIce/TPSL/GNU
INCLUDES='-I${NETCDF_DIR}/include -I${CRAY_MPICH_DIR}/include'
LIBS='-L${NETCDF_DIR}/lib -L${CRAY_MPICH_DIR}/include/lib'

INCLUDES="$INCLUDES -I${MY_PETSC_DIR}/include -I${MY_PETSC_DIR}/include/petsc "

LIBS="$LIBS -L${MY_PETSC_DIR}/lib -lpetsc -lHYPRE -lcmumps -ldmumps -lesmumps -lsmumps -lzmumps -lmumps_common -lptesmumps -lesmumps -lpord -lsuperlu -lsuperlu_dist -lptscotch -lscotch -lptscotcherr -lscotcherr -lparmetis -lmetis -lm -lstdc++"
###

NOOPTFLAGS='-O0'
NOOPTFILES=''

FFLAGS='-fallow-argument-mismatch -I${MY_PETSC_DIR}/include'

if test "x$IEEE" = x ; then   #- with optimisation:
    FOPTIM='-O3'
else
    if test "x$DEVEL" = x ; then  #- no optimisation + IEEE :
      FOPTIM='-O0'
    else                          #- development/check options:
      FOPTIM='-O0 -g'
    fi
fi

# added following truncation errors in TAF
# need retest ECCO without TAF

FFLAGS="$FFLAGS -mcmodel=medium"
CFLAGS="$CFLAGS -mcmodel=medium"
